---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.application_name }}
  name: {{ .Values.application_name }}
  namespace: {{ .Values.build.namespace }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.application_name }}
  name: {{ .Values.application_name }}
  namespace: {{ .Values.build.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.application_name }}:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.build.image_stream_name }}
        namespace: {{ .Values.build.image_stream_namespace }}
    type: Source
