---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: {{ .Values.pipeline.namespace }}
stringData:
  token: {{ .Values.pipeline.webhook_secret_key }}
  secret: {{ .Values.pipeline.webhook_secret_val }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ .Release.Name }}-build-triggertemplate
  namespace: {{ .Values.pipeline.namespace }}
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: {{ .Values.pipeline.source_ref }}
    - name: gitrepositoryurl
      description: The git repository url
      default: {{ .Values.pipeline.source_repo }} 
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: {{ .Release.Name }}-git-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
        - name: sslVerify
          value: "false"
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: {{ .Release.Name }}-build-pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: {{ .Release.Name }}-pipeline
        serviceAccountNames:
          - taskName: build-image
            serviceAccountName: {{ .Release.Name }}-sa
        params:
          - name: imageTag
            value: $(params.gitrevision)
          - name: SONAR_URL
            value: {{ .Values.sonar.route }}
          - name: SONAR_USER
            value: {{ .Values.sonar.username }}
          - name: SONAR_PASSWORD
            value: {{ .Values.sonar.password }}
        resources:
          - name: {{ .Release.Name }}-git
            resourceRef:
              name: {{ .Release.Name }}-git-$(uid)
        workspaces:
        - name: local-tssc-repo
          emptyDir: {}
          # persistentVolumeClaim:
          #  claimName: tssc-pipe-storage
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ .Release.Name }}-pipelinebinding
  namespace: {{ .Values.pipeline.namespace }}
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Release.Name }}-webhook
  namespace: {{ .Values.pipeline.namespace }}
spec:
  serviceAccountName: {{ .Release.Name }}-sa
  triggers:
  - bindings:
    - name: {{ .Release.Name }}-pipelinebinding
    template:
      name: {{ .Release.Name }}-build-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Release.Name }}-webhook
  name: webhook-{{ .Release.Name }}
  namespace: {{ .Values.pipeline.namespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Release.Name }}-webhook
    weight: 100
  wildcardPolicy: None
