labitems:
- name: ocp-demo-cluster
  type: ocp4
  config-dir: ocp-demo-cluster
  description: Openshift cluster used to demo ATT functionality ocp-admin, R3dHat123!
  url: https://console-openshift-console.apps.att-demo.ocp-labs.rhtelco.io
  vars: []
- name: labs-pipeline-operators
  type: helm
  config-dir: pipeline-operators
  description: Installs Tekton and ArgoCd for Pipeline support, Argocd in namespace labs-cicd
  vars:
     namespace:
       value: labs-cicd
       description: Namespace to install argocd
  url: https://labs.rhtelco.io
