---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: {{ .Values.pipeline.namespace }}
stringData:
  token: {{ .Values.pipeline.webhook_secret_key }}
  secret: {{ .Values.pipeline.webhook_secret_val }}
