---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: mikes-test
  name: create-pull-request
  namespace: att-pipelines
spec:
  params:
    - name: filePath
      description: The expected value
    - name: imageTag
      description: The url to curl
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: create-pull-request
    image: image-registry.openshift-image-registry.svc:5000/att-pipelines/pull-request-task:latest
    env:
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-secret
          key: username
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secret
          key: token
    script: |
       #!/usr/bin/env bash
       echo "Hello from Bash!"
       cd source 
       echo "Updating file: $(params.filePath)"
       GIT_URL=$(resources.inputs.source.url)
       echo "URL: $GIT_URL"
       GIT_PATH="${GIT_URL#*//}"
       git remote set-url origin "https://$GIT_USERNAME:$GIT_TOKEN@$GIT_PATH"
       git config --global user.email "$GIT_USERNAME@redhat.com"
       git config --global user.name "$GIT_USERNAME"
       mkdir ~/.config
       cat > ~/.config/hub << EOF3
       github.com:
       - user: $GIT_USERNAME
         oauth_token: $GIT_TOKEN
         protocol: https
       EOF3
       git checkout qa
       ls -lrt
       NEW_VAL=$(params.imageTag)
       ls -lrt ./.openshift
       REPLACE_VAL=$(awk '/name: application_tag/{getline; print}' ./.openshift/spring-boot-demo.yaml)
       echo "FOO: $REPLACE_VAL"
       sed -i "s/$REPLACE_VAL/$NEW_VAL/" ./.openshift/spring-boot-demo.yaml
       cat ./.openshift/spring-boot-demo.yaml
       git add $(params.filePath)
       git branch -m qa-$(params.imageTag)
       git commit -m "Updating QA Tag to $(params.imageTag)"
       git push origin qa-$(params.imageTag):qa-$(params.imageTag)
       hub pull-request -m qa-$(params.imageTag) -b qa
       echo "Pull Request created for branch qa-$(params.imageTag)"
