---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: mikes-test
  name: create-pull-request
  namespace: {{ .Values.pipeline.namespace }}
spec:
  params:
    - name: filePath
      description: The expected value
    - name: imageTag
      description: The url to curl
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: create-pull-request
    image: image-registry.openshift-image-registry.svc:5000/{{ .Values.pipeline.namespace }}/pull-request-task:latest
    env:
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-secret
          key: username
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secret
          key: token
    script: |
       #!/usr/bin/env bash
       echo "Hello from Bash!"
       cd source 
       echo "Updating file: $(params.filePath)"
       GIT_URL=$(resources.inputs.source.url)
       echo "URL: $GIT_URL"
       GIT_PATH="${GIT_URL#*//}"

       NEW_URL=$(echo https://$GIT_USERNAME:$GIT_TOKEN@$GIT_PATH|tr -d ' \n')
       echo "GIT NEW URL: $NEW_URL"
       git remote set-url origin $NEW_URL
       git config --global user.email "$GIT_USERNAME@redhat.com"
       git config --global user.name "$GIT_USERNAME"
       git config credential.helper 'cache --timeout=30'
       mkdir ~/.config
       cat > ~/.config/hub << EOF3
       github.com:
       - user: $GIT_USERNAME
         oauth_token: $GIT_TOKEN
         protocol: https
       EOF3
       git fetch
       LAST_COMMIT=$(git log -1 --pretty=%B)
       git checkout qa
       ls -lrt
       NEW_VAL=$(params.imageTag)
       ls -lrt ./.openshift
       REPLACE_VAL=$(awk '/name: application_tag/{getline; print}' ./.openshift/spring-boot-demo.yaml)
       REPLACE_VAL=${REPLACE_VAL#*:}
       echo "FOO: $REPLACE_VAL"
       sed -i "s/$REPLACE_VAL/ $NEW_VAL/" ./.openshift/spring-boot-demo.yaml
       cat ./.openshift/spring-boot-demo.yaml
       git add $(params.filePath)
       git branch -m qa-$(params.imageTag)
       git commit -m "Updating QA Tag to $(params.imageTag)"
       git push origin qa-$(params.imageTag):qa-$(params.imageTag)
       if [[ $? -ne 0 ]]; 
       then
         echo "Failed Creating PR, most likely invalid Git Token"
         exit 1
       fi
       hub pull-request -m "$LAST_COMMIT" -b qa
       echo "Pull Request created for [$LAST_COMMIT] on branch qa"
