apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-pom-version
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "pomversion"
spec:
  description: >-
    Given a base version, this task generates a unique build id by appending
    the base-version to the current timestamp.
  params:
    - name: default-version
      description: Base product version
      type: string
      default: "1.0"
  resources:
    inputs:
    - name: source
      type: git      
  results:
    - name: pom-version
      description: Version of pom artifact
  steps:
    - name: mvn-version
      image: maven:3.6.0-jdk-8-slim
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        MVN_VERSION=$(/usr/bin/mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        echo $MVN_VERSION | tr -d "\n" | tee $(results.pom-version.path)
