{{- if eq .Values.sonar.enabled true }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: {{ .Values.sonar.name }}
    app: {{ template "pipeline-tools.name" . }}
  name: {{ .Values.sonar.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: {{ .Values.sonar.name }}
    app: {{ template "pipeline-tools.name" . }}
    type: "image"
  name: {{ .Values.sonar.name }}
  namespace: {{ .Values.namespace }}
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.sonar.name }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: "{{ .Values.sonar.build.source_context_dir }}"
    git:
      ref: "{{ .Values.sonar.build.source_repository_ref }}"
      uri: "{{ .Values.sonar.build.source_repository_url }}"
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.sonar.build.from_docker_image_registry_url }}:{{ .Values.sonar.build.from_docker_tag }}
  triggers:
  - type: ConfigChange
  - type: ImageChange

{{- end }}


