{{- if not .Values.remove_config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-demo
  namespace: openshift-config
data:
  htpasswd: bWxhY291cnNlOiRhcHIxJEJ0RjhCVXRKJHUvOTQwbk5vV3EuMHpocFk4S1RqaDEKZGt5cHVyb3M6e1NIQX1uUHIwK3VZRTI4Y21UU1plblZhUDd0MmlvdFU9CnJoYWRkYWQ6e1NIQX1uUHIwK3VZRTI4Y21UU1plblZhUDd0MmlvdFU9Cmd1ZXN0OntTSEF9blByMCt1WUUyOGNtVFNaZW5WYVA3dDJpb3RVPQo=
{{- end }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
{{- if .Values.remove_config }}
  {}
{{ else }}
  identityProviders:
  - name: htpasswd 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-demo
{{ end }} 
