{{- if not .Values.remove_config }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: att-lab-user-roles
  namespace: {{ .Values.namespace }}
subjects:
  - kind: User
    name: mlacourse
  - kind: User
    name: dkypuros
  - kind: User
    name: rhaddad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}
