{{- if .Values.build.deploy }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{.Release.Name }}
  namespace: {{ .Values.build.namespace }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: {{.Release.Name }}
  name: {{.Release.Name }}
  namespace: {{ .Values.build.namespace }}
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Release.Name }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.build.image_stream_name }}
        namespace: {{ .Values.build.image_stream_namespace }}
    type: Source
  successfulBuildsHistoryLimit: 5
{{- end }}  
