{{- if .Values.pipeline.googlechat_token }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pipeline.googlechat_secret }}
  namespace: {{ .Values.pipeline.namespace }}
stringData:
  key: {{ .Values.pipeline.googlechat_key }}
  token: {{ .Values.pipeline.googlechat_token }}
  channel: {{ .Values.pipeline.googlechat_channel }}
{{- end }}
