---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-argocd-role
  namespace: {{ .Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: {{ .Values.argocd_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

