apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  jgroups-cluster-password:
    {{ .Values.jgroupsClusterPassword | b64enc }}
{{- if .Values.tls.enabled }}
  jgroups-encrypt-password:
    {{ .Values.tls.jgroupsEncryptPassword | b64enc }}
  https-encrypt-password:
    {{ .Values.tls.httpsPassword | b64enc }}
{{- end }}
