---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.tools_namespace }}
spec:
  destination:
    namespace: {{ .Values.pipeline_namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: sonar.route
          value: >-
            {{ .Values.sonar_route }}
        - name: pipeline.tools_namespace
          value: {{ .Values.tools_namespace }}
        - name: pipeline.github_secret_username
          value: {{ .Values.github_secret_username }}
        - name: pipeline.github_secret_token
          value: {{ .Values.github_secret_token }}
        - name: pipeline.googlechat_token
          value: {{ .Values.googlechat_token }}
        - name: pipeline.googlechat_key
          value: {{ .Values.googlechat_key }}
        - name: pipeline.googlechat_channel
          value: {{ .Values.googlechat_channel }}
    path: helm/pipeline-samples/tekton-pipelines
    repoURL: 'https://github.com/redhat-mal/ocp-labs-manager.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
  
